"""
services/api/mint.py

Python helper that calls the deployed ChainPortrait contract from the
SigilX API backend.

Triggered when a user clicks "Mint" — after a portrait has been generated —
to record it permanently on X Layer.

Requires:
  - web3.py:  pip install web3
  - Contract ABI in contracts/artifacts/ChainPortrait.json (after `npm run compile`)
  - XLAYER_RPC_URL, XLAYER_PRIVATE_KEY, CHAIN_PORTRAIT_ADDRESS_* in .env
"""

from __future__ import annotations

import hashlib
import json
import os
import time
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from .ipfs import upload_png_to_ipfs, upload_json_to_ipfs
from ..extractor.fingerprint import FeatureVector
from ..renderer.attractor import render_attractor_png

load_dotenv()

try:
    from web3 import Web3
    from web3.middleware import ExtraDataToPOAMiddleware
    WEB3_AVAILABLE = True
except ImportError:
    WEB3_AVAILABLE = False

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

XLAYER_RPC_URL = os.getenv("XLAYER_RPC_URL", "https://testrpc.xlayer.tech/terigon")
XLAYER_PRIVATE_KEY = os.getenv("XLAYER_PRIVATE_KEY", "")

# Address switches based on network
_TESTNET_ADDR = os.getenv("CHAIN_PORTRAIT_ADDRESS_TESTNET", "")
_MAINNET_ADDR = os.getenv("CHAIN_PORTRAIT_ADDRESS_MAINNET", "")

# Determine which address to use based on RPC URL
CONTRACT_ADDRESS = (
    _MAINNET_ADDR if "testnet" not in XLAYER_RPC_URL and "testrpc" not in XLAYER_RPC_URL
    else _TESTNET_ADDR
)

# Path to compiled ABI (generated by `npm run compile` in contracts/)
ABI_PATH = Path(__file__).parent.parent.parent / "contracts" / "artifacts" / "src" / "SigilX.sol" / "SigilX.json"


# ---------------------------------------------------------------------------
# MintResult
# ---------------------------------------------------------------------------

class MintResult:
    def __init__(
        self,
        success: bool,
        tx_hash: str = "",
        token_id: int = 0,
        error: str = "",
        block_number: int = 0,
        explorer_url: str = "",
    ):
        self.success = success
        self.tx_hash = tx_hash
        self.token_id = token_id
        self.error = error
        self.block_number = block_number
        self.explorer_url = explorer_url

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "tx_hash": self.tx_hash,
            "token_id": self.token_id,
            "block_number": self.block_number,
            "explorer_url": self.explorer_url,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# Main mint function
# ---------------------------------------------------------------------------

async def mint_portrait(
    to_address: str,
    wallet_address: str,
    source_chain: str,
    portrait_id: str,
    svg: str,
    feature_vector: dict,
    tx_count: int,
    mint_fee_wei: int = 0,
) -> MintResult:
    """
    Mint a Chain Portrait NFT on X Layer.

    Args:
        to_address:     Recipient wallet address.
        wallet_address: The analyzed wallet address.
        source_chain:   Source chain (e.g. "eth-mainnet").
        portrait_id:    Deterministic portrait ID.
        svg:            Full SVG string (used to compute svgHash).
        feature_vector: Dict of 8 feature dimensions.
        tx_count:       Number of transactions analyzed.
        mint_fee_wei:   Mint fee in wei (OKB).

    Returns:
        MintResult with success flag, tx_hash, token_id, etc.
    """
    if not WEB3_AVAILABLE:
        return MintResult(
            success=False,
            error="web3 not installed. Run: pip install web3"
        )

    if not XLAYER_PRIVATE_KEY:
        return MintResult(
            success=False,
            error="XLAYER_PRIVATE_KEY not set in environment"
        )

    if not CONTRACT_ADDRESS:
        return MintResult(
            success=False,
            error="Contract address not set. Deploy first and set CHAIN_PORTRAIT_ADDRESS_TESTNET or _MAINNET"
        )

    try:
        w3, contract = _get_contract()

        # Compute SVG hash (keccak256)
        svg_hash_hex = w3.keccak(text=svg).hex()
        # Convert to bytes32 for contract call
        svg_hash_bytes = bytes.fromhex(svg_hash_hex[2:] if svg_hash_hex.startswith("0x") else svg_hash_hex)

        # Feature vector as JSON string
        fv_json = json.dumps(feature_vector, separators=(",", ":"))

        # Render the actual displayed artwork as a raster PNG — a Clifford
        # strange-attractor point-cloud, seeded the same deterministic way as
        # the on-chain SVG (SHA-256 of wallet+chain). PNG rather than SVG both
        # matches the intended chaos-math visual density and sidesteps SVG
        # rendering support gaps in some explorers (e.g. OKLink).
        png_bytes = render_attractor_png(wallet_address, source_chain, FeatureVector(**feature_vector))

        # Pin the PNG to IPFS so explorers/marketplaces that don't render inline
        # data URIs (e.g. OKLink) can still display the image. tokenURI() falls
        # back to the on-chain SVG data URI if this comes back empty.
        image_uri = await upload_png_to_ipfs(png_bytes, portrait_id) or ""

        # Also pin the full metadata JSON — most explorers only index tokenURI()
        # when it's a real http(s)/ipfs link, not an inline data URI, so pinning
        # just the image isn't enough for the image to actually render there.
        # tokenId/mintedAt aren't known until the mint tx is mined, so this uses
        # portrait_id/generated-at-request-time in their place rather than doing
        # a second on-chain update transaction after confirmation.
        metadata_uri = ""
        if image_uri:
            metadata = {
                "name": f"SigilX · {portrait_id}",
                "description": (
                    "A unique, deterministic artwork generated from the on-chain behavioral "
                    f"fingerprint of wallet {wallet_address[:6]}...{wallet_address[-4:]} on "
                    f"{source_chain}. Generated by SigilX - built on OKX Market API + X Layer."
                ),
                "external_url": f"https://sigilx.xyz/portrait/{portrait_id}",
                "image": image_uri,
                "attributes": [
                    {"trait_type": "Source Chain", "value": source_chain},
                    {"trait_type": "Portrait ID", "value": portrait_id},
                    {"trait_type": "SVG Hash", "value": svg_hash_hex if svg_hash_hex.startswith("0x") else f"0x{svg_hash_hex}"},
                    {"trait_type": "Transactions Analyzed", "display_type": "number", "value": tx_count},
                    {"trait_type": "Generated At", "display_type": "date", "value": int(time.time())},
                    {"trait_type": "Wallet", "value": wallet_address},
                ],
            }
            metadata_uri = await upload_json_to_ipfs(metadata, portrait_id) or ""

        # Build transaction
        account = w3.eth.account.from_key(XLAYER_PRIVATE_KEY)
        nonce = w3.eth.get_transaction_count(account.address)

        mint_fn = contract.functions.mint(
            w3.to_checksum_address(to_address),
            w3.to_checksum_address(wallet_address),
            source_chain,
            portrait_id,
            svg_hash_bytes,
            fv_json,
            tx_count,
            svg,
            image_uri,
            metadata_uri,
        )

        # Gas cost varies with string lengths (portraitId, featureVector JSON, svg, etc.)
        # so estimate per-call rather than trusting a fixed value — a hardcoded
        # gas limit here previously caused mint transactions to revert out-of-gas.
        estimated_gas = mint_fn.estimate_gas({"from": account.address, "value": mint_fee_wei})
        gas_limit = int(estimated_gas * 1.2)

        tx = mint_fn.build_transaction({
            "from": account.address,
            "value": mint_fee_wei,
            "nonce": nonce,
            "gas": gas_limit,
            "gasPrice": w3.eth.gas_price,
        })

        # Sign and send
        signed = w3.eth.account.sign_transaction(tx, XLAYER_PRIVATE_KEY)
        tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
        tx_hash_hex = "0x" + tx_hash.hex()

        # Wait for confirmation (max 60 seconds)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)

        if receipt["status"] != 1:
            return MintResult(
                success=False,
                tx_hash=tx_hash_hex,
                error="Transaction reverted on-chain",
            )

        # Extract tokenId from PortraitMinted event
        token_id = _extract_token_id(contract, receipt)

        is_testnet = "1952" in XLAYER_RPC_URL or "testrpc" in XLAYER_RPC_URL
        explorer_base = "https://www.oklink.com/xlayer-test" if is_testnet else "https://www.oklink.com/xlayer"

        return MintResult(
            success=True,
            tx_hash=tx_hash_hex,
            token_id=token_id,
            block_number=receipt["blockNumber"],
            explorer_url=f"{explorer_base}/tx/{tx_hash_hex}",
        )

    except Exception as e:
        return MintResult(success=False, error=str(e))


# ---------------------------------------------------------------------------
# Mint route (add to routes.py)
# ---------------------------------------------------------------------------

class MintRequest:
    """Used by routes.py to accept mint requests."""
    def __init__(self, portrait_id: str, to_address: str):
        self.portrait_id = portrait_id
        self.to_address = to_address


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_contract():
    """Initialize web3 and the contract instance."""
    w3 = Web3(Web3.HTTPProvider(XLAYER_RPC_URL))
    # X Layer is PoA-based — inject PoA middleware
    w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)

    if not w3.is_connected():
        raise RuntimeError(f"Cannot connect to X Layer RPC: {XLAYER_RPC_URL}")

    abi = _load_abi()
    contract = w3.eth.contract(
        address=w3.to_checksum_address(CONTRACT_ADDRESS),
        abi=abi,
    )
    return w3, contract


def _load_abi() -> list:
    """Load contract ABI from compiled artifact."""
    if not ABI_PATH.exists():
        raise FileNotFoundError(
            f"Contract ABI not found at {ABI_PATH}. "
            "Run `npm run compile` in the contracts/ directory first."
        )
    with open(ABI_PATH) as f:
        artifact = json.load(f)
    return artifact.get("abi", artifact)


def _extract_token_id(contract, receipt) -> int:
    """Extract tokenId from the PortraitMinted event in the receipt."""
    try:
        logs = contract.events.PortraitMinted().process_receipt(receipt)
        if logs:
            return int(logs[0]["args"]["tokenId"])
    except Exception:
        pass
    return 0


# ---------------------------------------------------------------------------
# Mint status check
# ---------------------------------------------------------------------------

async def get_portrait_token_id(portrait_id: str) -> Optional[int]:
    """
    Check if a portrait has been minted and return its tokenId (or None).
    """
    if not WEB3_AVAILABLE or not CONTRACT_ADDRESS:
        return None
    try:
        _, contract = _get_contract()
        token_id = contract.functions.getTokenByPortraitId(portrait_id).call()
        return int(token_id) if token_id != 0 else None
    except Exception:
        return None
